name: "Quick Version"
description: "A simple version generate that uses commit comments and settings file to compute the next version."

inputs:
  version-label:
    description: "The version label to append, e.g., 'rc' or 'beta'. If empty, no label is appended."
    required: false
    default: ""
  build-metadata:
    description: "The build metadata to append, e.g., 'sha1234567'. If empty, no build metadata is appended."
    required: false
    default: ""
  include-paths:
    description: "Semicolon-separated glob/prefix patterns to INCLUDE commits by changed paths (e.g. src/;lib/). Empty = include all commits."
    required: false
    default: "src/;lib/;source/"
  exclude-paths:
    description: "Semicolon-separated glob/prefix patterns to EXCLUDE commits by changed paths (e.g. docs/;test/)."
    required: false
    default: ".github/;tests/;docs/"

outputs:
  major:
    description: "The major version number"
    value: ${{ steps.compute.outputs.major }}
  minor:
    description: "The minor version number"
    value: ${{ steps.compute.outputs.minor }}
  patch:
    description: "The patch version number"
    value: ${{ steps.compute.outputs.patch }}
  version:
    description: "The full version number in the format #.#.#.#"
    value: ${{ steps.compute.outputs.version }}
  label:
    description: "The version label, e.g., rc.1+sha3efddf..."
    value: ${{ steps.compute.outputs.label }}   # <-- fixed (was major)
  infoVersion:
    description: "The informational vesion in the format #.#.#.#-LABEL, e.g., 1.2.3.4-rc.1+sha3efddf..."
    value: ${{ steps.compute.outputs.infoVersion }}

runs:
  using: "composite"
  steps: 
    - id: compute
      shell: pwsh
      env:
        INPUT_VERSION_LABEL: ${{ inputs.version-label }}
        INPUT_BUILD_METADATA: ${{ inputs.build-metadata }}
        INPUT_INCLUDE_PATHS: ${{ inputs.include-paths }}
        INPUT_EXCLUDE_PATHS: ${{ inputs.exclude-paths }}      
      run: |
          # check correct shallow file path
          if (Test-Path ".git/shallow") {
            Write-Warning "A non-shallow checkout must be done prior to using quick-version, i.e., fetch-depth: 0"
            exit 1
          }

          . (Join-Path $env:GITHUB_ACTION_PATH 'action-compute.ps1')